In [1]:
import pandas as pd
# train = pd.read_csv("train.csv")
# test = pd.read_csv("ltest.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/test.csv")

In [2]:
train.shape, test.shape

((3759, 9), (1617, 8))

In [3]:
train.head(3)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,EcoSport,2017,10298,Manual,25013,Petrol,150,53.3,1.0
1,Focus,2016,10491,Manual,30970,Diesel,0,74.3,1.5
2,S-MAX,2017,13498,Manual,60200,Diesel,150,56.5,2.0

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3759 entries, 0 to 3758
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         3759 non-null   object
 1   year          3759 non-null   int64
 2   price         3759 non-null   int64
 3   transmission  3759 non-null   object
 4   mileage       3759 non-null   int64
 5   fuelType      3759 non-null   object
 6   tax           3759 non-null   int64
 7   mpg           3759 non-null   float64
 8   engineSize    3759 non-null   float64
dtypes: float64(2), int64(4), object(3)
memory usage: 264.4+ KB

In [5]:
train.describe()

,year,price,mileage,tax,mpg,engineSize
count,3759.000000,3759.000000,3759.000000,3759.000000,3759.000000,3759.000000
mean,2016.887736,12353.321362,23191.786379,114.444001,57.793083,1.352807
std,2.151811,4750.338051,19223.258713,61.713682,10.099221,0.437130
min,2002.000000,1095.000000,5.000000,0.000000,20.900000,0.000000
25%,2016.000000,9000.000000,9997.500000,75.000000,52.300000,1.000000
50%,2017.000000,11495.000000,18180.000000,145.000000,58.900000,1.200000
75%,2018.000000,15310.000000,31000.000000,145.000000,65.700000,1.500000
max,2060.000000,48000.000000,144000.000000,570.000000,201.800000,5.000000

In [8]:
train.describe(include='object')

          model transmission fuelType
count      3759         3759     3759
unique       19            3        3
top      Fiesta       Manual   Petrol
freq       1372         3234     2541

In [9]:
train.isnull().sum().sum()

np.int64(0)

In [10]:
test.isnull().sum().sum()

np.int64(0)

In [11]:
target=train.pop('price')

print(train.shape, test.shape)
train=pd.get_dummies(train)
test=pd.get_dummies(test)
print(train.shape, test.shape)

(3759, 8) (1617, 8)
(3759, 30) (1617, 30)

In [13]:
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)
print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)

(3007, 30) (752, 30) (3007,) (752,)

In [15]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

rf = RandomForestRegressor(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

rmse = np.sqrt(mean_squared_error(y_val, pred))
print(f"RMSE: {rmse}")

RMSE: 1341.943732584459

In [16]:
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

In [17]:
print(pd.read_csv("result.csv").head())

       pred
0  15586.88
1  15407.71
2  14912.47
3  18482.73
4   6168.01